public class Recommendation {
    private final boolean isAutoGenerated;
    private final String type;
    private final Song song;
    private final User fromUser;
    private final User toUser;

    public Recommendation(boolean isAutoGenerated, String type, Song song, User fromUser, User toUser) {
        this.isAutoGenerated = isAutoGenerated;
        this.type = type;
        this.song = song;
        this.fromUser = fromUser;
        this.toUser = toUser;
    }

    public String getType() {
        return type;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public Song getSong() {
        return song;
    }

    public User getFromUser() {
        return fromUser;
    }

    public User getToUser() {
        return toUser;
    }
}
